### ISSUE TITLE
Use known "good" photos

### ISSUE THREAD

**Issue by fangeugene** [ErikBoesen/FRCNewTab#19]
Depends on https://github.com/the-blue-alliance/the-blue-alliance/issues/1625

**Comment by ErikBoesen** [comment]
This is definitely something I'd like to get done, please do tell me when this feature is implemented into TBA.

**Comment by umer936** [comment]
https://github.com/umer936/FRCNewTab/commit/a4219b461b65ae92b3716dad3e04726a6127b032 

Potentially done; however, unsure of whether if it is required for the team to have a "required" media. Just asked @fangeugene on Slack.
