### ISSUE TITLE
Feature Request: Search Box?

### ISSUE THREAD

**Issue by MC42** [ErikBoesen/FRCNewTab#22]
Someone on Chief Delphi requested a simple search box on the main page to replace their new tab window fully.  Would this be doable as a toggleable option?

https://www.chiefdelphi.com/forums/showpost.php?p=1608610&postcount=18

**Comment by ErikBoesen** [comment]
lol who uses the search box

I kid, this sounds like a good feature. Want to add it?

**Comment by jaredhasenklein** [comment]
Haha this was me...

**Comment by Samcfuchs** [comment]
@jaredhasenklein `<C-l>`

**Comment by ErikBoesen** [comment]
I'd recommend using the Omnibox.
