### ISSUE TITLE
New tab renders broken imgur uploads

### ISSUE THREAD

**Issue by Samcfuchs** [ErikBoesen/FRCNewTab#29]
![](https://i.gyazo.com/bc14f846cb1d65728cdc8213d3d50bd6.png)

As you can see, it is rendering imgur's "image missing" link. I think this should be ignored.

**Comment by ErikBoesen** [comment]
Oh dear.

**Comment by Samcfuchs** [comment]
It's not every one, just for certain teams.

**Comment by ErikBoesen** [comment]
Nothing we can do about this.
